### PR TITLE
Test application with Maven in CI

### PR DESCRIPTION
**Pull request by vradovic**
This PR adds the step to test the application with Maven to the CI.

### CODE REVIEW

**Comment by duolok** [comment]
I'm not sure we need this. But I would let this PR stay open anyway.

**Comment by vradovic** [comment]
> I'm not sure we need this. But I would let this PR stay open anyway.

I think we do need it because we have unit tests. This would run the tests to make sure everything is working.

**Comment by MomirMilutinovic** [comment]
Doesn't Maven Build already run unit tests?

**Comment by vradovic** [comment]
> Doesn't Maven Build already run unit tests?

No, you can see in the workflow before it was only building the project.

**Pull request closed without merging**
